import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Providers from "@/lib/providers";

const lydian = localFont({
  src: './Lydian BT.woff2',
  display: 'swap',
})

const questa = localFont({
  src: './Questa_Sans_Regular.woff2',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/wcx8exc.css"></link>
      </head>
      <body
        className={`${lydian.className} ${questa.className} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
